export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT = 'LOGOUT';

export const GET_PROFILE_REQUEST = 'PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'PROFILE_FAILURE';
