export default [
    'A# .NET',
    'A-0 System',
    'A+',
    'A++',
    'ABAP',
    'ABC',
    'ABC ALGOL',
    'ABSET',
    'ABSYS',
    'ACC',
    'Accent',
    'Ace DASL (Distributed Application Specification Language)',
    'ACL2',
    'ACT-III',
    'Action!',
    'ActionScript',
    'Actor',
    'Ada',
    'Adenine',
    'Agda',
    'Agilent VEE',
    'Agora',
    'AIMMS',
    'Aldor',
    'Alef',
    'ALF',
    'ALGOL 58',
    'ALGOL 60',
    'ALGOL 68',
    'ALGOL W',
    'Alice',
    'Alma-0',
    'AmbientTalk',
    'Amiga E',
    'AMOS',
    'AMPL',
    'AngelScript',
    'Apex',
    'APL',
    'App Inventor for Android\'s visual block language',
    'AppleScript',
    'APT',
    'Arc',
    'ARexx',
    'Argus',
    'AspectJ',
    'Assembly language',
    'ATS',
    'Ateji PX',
    'AutoHotkey',
    'Autocoder',
    'AutoIt',
    'AutoLISP / Visual LISP',
    'Averest',
    'AWK',
    'Axum',
    'Active Server Pages',
    'B',
    'B',
    'Babbage',
    'Ballerina',
    'Bash',
    'BASIC',
    'bc',
    'BCPL',
    'BeanShell',
    'Batch file (Windows/MSDOS)',
    'Bertrand',
    'BETA',
    'BLISS',
    'Blockly',
    'BlooP',
    'Boo',
    'Boomerang',
    'Bourne shell (including bash and ksh)',
    'BPEL',
    'Business Basic',
    'C',
    'C',
    'C--',
    'C++',
    'C*',
    'C#',
    'C/AL',
    'Caché ObjectScript',
    'C Shell (csh)',
    'Caml',
    'Cayenne',
    'CDuce',
    'Cecil',
    'Cesil',
    'Céu',
    'Ceylon',
    'CFEngine',
    'Cg',
    'Ch',
    'Chapel',
    'Charity',
    'Charm',
    'CHILL',
    'CHIP-8',
    'chomski',
    'ChucK',
    'Cilk',
    'Citrine',
    'CL (IBM)',
    'Claire',
    'Clarion',
    'Clean',
    'Clipper',
    'CLIPS',
    'CLIST',
    'Clojure',
    'CLU',
    'CMS-2',
    'COBOL',
    'CobolScript – COBOL Scripting language',
    'Cobra',
    'CoffeeScript',
    'ColdFusion',
    'COMAL',
    'Combined Programming Language (CPL)',
    'COMIT',
    'Common Intermediate Language (CIL)',
    'Common Lisp (also known as CL)',
    'COMPASS',
    'Component Pascal',
    'Constraint Handling Rules (CHR)',
    'COMTRAN',
    'Cool',
    'Coq',
    'Coral 66',
    'CorVision',
    'COWSEL',
    'CPL',
    'Cryptol',
    'Crystal',
    'Csound',
    'CSP',
    'Cuneiform',
    'Curl',
    'Curry',
    'Cybil',
    'Cyclone',
    'Cython',
    'D',
    'D',
    'DASL (Datapoint\'s Advanced Systems Language)',
    'Dart',
    'Darwin',
    'DataFlex',
    'Datalog',
    'DATATRIEVE',
    'dBase',
    'dc',
    'DCL',
    'DinkC',
    'DIBOL',
    'Dog',
    'Draco',
    'Dragon',
    'DRAKON',
    'Dylan',
    'DYNAMO',
    'DAX (Data Analysis Expressions)',
    'E',
    'E',
    'Ease',
    'Easy PL/I',
    'EASYTRIEVE PLUS',
    'eC',
    'ECMAScript',
    'Edinburgh IMP',
    'EGL',
    'Eiffel',
    'ELAN',
    'Elixir',
    'Elm',
    'Emacs Lisp',
    'Emerald',
    'Epigram',
    'EPL (Easy Programming Language)',
    'EPL (Eltron Programming Language)',
    'Erlang',
    'es',
    'Escher',
    'ESPOL',
    'Esterel',
    'Etoys',
    'Euclid',
    'Euler',
    'Euphoria',
    'EusLisp Robot Programming Language',
    'CMS EXEC (EXEC)',
    'EXEC 2',
    'Executable UML',
    'Ezhil',
    'F',
    'F',
    'F#',
    'F*',
    'Factor',
    'Fantom',
    'FAUST',
    'FFP',
    'Fjölnir',
    'FL',
    'Flavors',
    'Flex',
    'FlooP',
    'FLOW-MATIC',
    'FOCAL',
    'FOCUS',
    'FOIL',
    'FORMAC',
    '@Formula',
    'Forth',
    'Fortran',
    'Fortress',
    'FoxPro',
    'FP',
    'Franz Lisp',
    'F-Script',
    'Flutter',
    'G',
    'Game Maker Language',
    'GameMonkey Script',
    'GAMS',
    'GAP',
    'G-code',
    'GDScript',
    'Genie',
    'GDL',
    'GEORGE',
    'GLSL',
    'GNU E',
    'Go',
    'Go!',
    'GOAL',
    'Gödel',
    'Golo',
    'GOM (Good Old Mad)',
    'Google Apps Script',
    'Gosu',
    'GOTRAN',
    'GPSS',
    'GraphTalk',
    'GRASS',
    'Grasshopper',
    'Groovy',
    'H',
    'Hack',
    'HAGGIS',
    'HAL/S',
    'Halide (programming language)',
    'Hamilton C shell',
    'Harbour',
    'Hartmann pipelines',
    'Haskell',
    'Haxe',
    'Hermes',
    'High Level Assembly',
    'HLSL',
    'HolyC',
    'Hop',
    'Hopscotch',
    'Hope',
    'Hugo',
    'Hume',
    'HyperTalk',
    'I',
    'Io',
    'Icon',
    'IBM Basic assembly language',
    'IBM BASICA',
    'IBM HAScript',
    'IBM Informix-4GL',
    'IBM RPG',
    'Irineu',
    'IDL',
    'Idris',
    'Inform',
    'J',
    'J',
    'J#',
    'J++',
    'JADE',
    'JAL',
    'Janus (concurrent constraint programming language)',
    'Janus (time-reversible computing programming language)',
    'JASS',
    'Java',
    'JavaFX Script',
    'JavaScript',
    'JCL',
    'JEAN',
    'Join Java',
    'JOSS',
    'Joule',
    'JOVIAL',
    'Joy',
    'JScript',
    'JScript .NET',
    'Julia',
    'Jython',
    'K',
    'K',
    'Kaleidoscope',
    'Karel',
    'KEE',
    'Kixtart',
    'Klerer-May System',
    'KIF',
    'Kojo',
    'Kotlin',
    'KRC',
    'KRL',
    'KRL (KUKA Robot Language)',
    'KRYPTON',
    'Korn shell (ksh)',
    'Kodu',
    'Kv',
    'L',
    'LabVIEW',
    'Ladder',
    'LANSA',
    'Lasso',
    'Lava',
    'LC-3',
    'Legoscript',
    'LIL',
    'LilyPond',
    'Limbo',
    'Limnor',
    'LINC',
    'Lingo',
    'LINQ',
    'LIS',
    'LISA',
    'Lisp',
    'Lite-C',
    'Lithe',
    'Little b',
    'LLL',
    'Logo',
    'Logtalk',
    'LotusScript',
    'LPC',
    'LSE',
    'LSL',
    'LiveCode',
    'LiveScript',
    'Lua',
    'Lucid',
    'Lustre',
    'LYaPAS',
    'Lynx',
    'M',
    'M (alternative name for the MUMPS programming language)',
    'M2001',
    'M4',
    'M#',
    'Machine code',
    'MAD (Michigan Algorithm Decoder)',
    'MAD/I',
    'Magik',
    'Magma',
    'Maude system',
    'Maple',
    'MAPPER (now part of BIS)',
    'MARK-IV (now VISION:BUILDER)',
    'Mary',
    'MASM Microsoft Assembly x86',
    'MATH-MATIC',
    'Mathematica',
    'MATLAB',
    'Maxima (see also Macsyma)',
    'Max (Max Msp – Graphical Programming Environment)',
    'MaxScript internal language 3D Studio Max',
    'Maya (MEL)',
    'MDL',
    'Mercury',
    'Mesa',
    'Metafont',
    'MetaQuotes Language (MQL4/MQL5)',
    'MHEG-5 (Interactive TV programming language)',
    'Microcode',
    'MicroScript',
    'MIIS',
    'Milk (programming language)',
    'MIMIC',
    'Mirah',
    'Miranda',
    'MIVA Script',
    'ML',
    'Model 204',
    'Modelica',
    'Modula',
    'Modula-2',
    'Modula-3',
    'Mohol',
    'MOO',
    'Mortran',
    'Mouse',
    'MPD',
    'Mathcad',
    'MSIL – deprecated name for CIL',
    'MSL',
    'MUMPS',
    'MuPAD',
    'Mutan',
    'Mystic Programming Language (MPL)',
    'N',
    'NASM',
    'Napier88',
    'Neko',
    'Nemerle',
    'NESL',
    'Net.Data',
    'NetLogo',
    'NetRexx',
    'NewLISP',
    'NEWP',
    'Newspeak',
    'NewtonScript',
    'Nial',
    'Nice',
    'Nickle (NITIN)',
    'Nim',
    'NPL',
    'Not eXactly C (NXC)',
    'Not Quite C (NQC)',
    'NSIS',
    'Nu',
    'NWScript',
    'NXT-G',
    'O',
    'o:XML',
    'Oak',
    'Oberon',
    'OBJ2',
    'Object Lisp',
    'ObjectLOGO',
    'Object REXX',
    'Object Pascal',
    'Objective-C',
    'Objective-J',
    'Obliq',
    'OCaml',
    'occam',
    'occam-π',
    'Octave',
    'OmniMark',
    'Onyx',
    'Opa',
    'Opal',
    'OpenCL',
    'OpenEdge ABL',
    'OPL',
    'OpenVera',
    'OPS5',
    'OptimJ',
    'Orc',
    'ORCA/Modula-2',
    'Oriel',
    'Orwell',
    'Oxygene',
    'Oz',
    'P',
    'P',
    'P4',
    'P′′',
    'ParaSail (programming language)',
    'PARI/GP',
    'Pascal',
    'PCASTL',
    'PCF',
    'PEARL',
    'PeopleCode',
    'Perl',
    'PDL',
    'Perl 6',
    'Pharo',
    'PHP',
    'Pico',
    'Picolisp',
    'Pict',
    'Pig (programming tool)',
    'Pike',
    'PIKT',
    'PILOT',
    'Pipelines',
    'Pizza',
    'PL-11',
    'PL/0',
    'PL/B',
    'PL/C',
    'PL/I',
    'PL/M',
    'PL/P',
    'PL/SQL',
    'PL360',
    'PLANC',
    'Plankalkül',
    'Planner',
    'PLEX',
    'PLEXIL',
    'Plus',
    'POP-11',
    'POP-2',
    'PostScript',
    'PortablE',
    'POV-Ray SDL',
    'Powerhouse',
    'PowerBuilder – 4GL GUI application generator from Sybase',
    'PowerShell',
    'PPL',
    'Processing',
    'Processing.js',
    'Prograph',
    'PROIV',
    'Prolog',
    'PROMAL',
    'Promela',
    'PROSE modeling language',
    'PROTEL',
    'ProvideX',
    'Pro*C',
    'Pure',
    'PureBasic',
    'Pure Data',
    'Python',
    'Q',
    'Q (programming language from Kx Systems)',
    'Q# (Microsoft programming language)',
    'Qalb',
    'QtScript',
    'QuakeC',
    'QPL',
    'R',
    'R',
    'R++',
    'Racket',
    'RAPID',
    'Rapira',
    'Ratfiv',
    'Ratfor',
    'rc',
    'Reason',
    'REBOL',
    'Red',
    'Redcode',
    'REFAL',
    'REXX',
    'Ring',
    'Rlab',
    'ROOP',
    'RPG',
    'RPL',
    'RSL',
    'RTL/2',
    'Ruby',
    'RuneScript',
    'Rust',
    'S',
    'S',
    'S2',
    'S3',
    'S-Lang',
    'S-PLUS',
    'SA-C',
    'SabreTalk',
    'SAIL',
    'SALSA',
    'SAM76',
    'SAS',
    'SASL',
    'Sather',
    'Sawzall',
    'Scala',
    'Scheme',
    'Scilab',
    'Scratch',
    'Script.NET',
    'Sed',
    'Seed7',
    'Self',
    'SenseTalk',
    'SequenceL',
    'Serpent',
    'SETL',
    'SIMPOL',
    'SIGNAL',
    'SiMPLE',
    'SIMSCRIPT',
    'Simula',
    'Simulink',
    'Singularity',
    'SISAL',
    'SLIP',
    'SMALL',
    'Smalltalk',
    'SML',
    'Strongtalk',
    'Snap!',
    'SNOBOL (SPITBOL)',
    'Snowball',
    'SOL',
    'Solidity',
    'SOPHAEROS',
    'SPARK',
    'Speakeasy',
    'Speedcode',
    'SPIN',
    'SP/k',
    'SPS',
    'SQL',
    'SQR',
    'Squeak',
    'Squirrel',
    'SR',
    'S/SL',
    'Starlogo',
    'Strand',
    'Stata',
    'Stateflow',
    'Subtext',
    'SBL',
    'SuperCollider',
    'SuperTalk',
    'Swift (Apple programming language)',
    'Swift (parallel scripting language)',
    'SYMPL',
    'SystemVerilog',
    'T',
    'T',
    'TACL',
    'TACPOL',
    'TADS',
    'TAL',
    'Tcl',
    'Tea',
    'TECO',
    'TELCOMP',
    'TeX',
    'TEX',
    'TIE',
    'TMG, compiler-compiler',
    'Tom',
    'TOM',
    'Toi',
    'Topspeed',
    'TPU',
    'Trac',
    'TTM',
    'T-SQL',
    'Transcript',
    'TTCN',
    'Turing',
    'TUTOR',
    'TXL',
    'TypeScript',
    'Tynker',
    'U',
    'Ubercode',
    'UCSD Pascal',
    'Umple',
    'Unicon',
    'Uniface',
    'UNITY',
    'Unix shell',
    'UnrealScript',
    'V',
    'Vala',
    'Verilog',
    'VHDL',
    'Vim script',
    'Viper',
    'Visual Basic',
    'Visual Basic .NET',
    'Visual DataFlex',
    'Visual DialogScript',
    'Visual Fortran',
    'Visual FoxPro',
    'Visual J++',
    'Visual J#',
    'Visual LISP',
    'Visual Objects',
    'Visual Prolog',
    'VSXu',
    'W',
    'WATFIV, WATFOR',
    'WebAssembly',
    'WebDNA',
    'Whiley',
    'Winbatch',
    'Wolfram Language',
    'Wyvern',
    'X',
    'X++',
    'X10',
    'xBase',
    'xBase++',
    'XBL',
    'XC (targets XMOS architecture)',
    'xHarbour',
    'XL',
    'Xojo',
    'XOTcl',
    'XOD (programming language)',
    'XPath',
    'XPL',
    'XPL0',
    'XQuery',
    'XSB',
    'XSharp',
    'XSLT',
    'Xtend',
    'Y',
    'Yorick',
    'YQL',
    'Yoix',
    'Z',
    'Z notation',
    'Zebra, ZPL, ZPL2',
    'Zeno',
    'ZetaLisp',
    'ZOPL',
    'Zsh',
    'ZPL',
    'Z++',
    'ASP.NET Dynamic Data',
    'Base One Foundation Component Library (BFC)',
    'Component-based Scalable Logical Architecture (CSLA)',
    'MonoRail',
    'OpenRasta',
    'CppCMS',
    'Poco',
    'Tntnet',
    'Wt',
    'CFWheels',
    'ColdBox Platform',
    'ColdSpring',
    'Fusebox',
    'Model-Glue',
    'Caveman2',
    'vibe.d',
    'Phoenix',
    'Snap',
    'Yesod',
    'Bootstrap (front-end framework)',
    'Foundation (framework)',
    'Apache Click',
    'Apache OFBiz',
    'Apache Shale',
    'Apache Sling',
    'Apache Struts 2',
    'Apache Tapestry',
    'Apache Wicket',
    'AppFuse',
    'Brutos Framework',
    'Eclipse RAP',
    'FormEngine',
    'Grails',
    'Google Web Toolkit',
    'Hamlets',
    'ItsNat',
    'JavaServer Faces (Mojarra)',
    'JBoss Seam',
    'Jspx-bay',
    'JVx',
    'JWt',
    'Netty (software)',
    'OpenLaszlo',
    'OpenXava',
    'Oracle ADF',
    'Play',
    'RIFE',
    'Spark',
    'Spring',
    'Stripes',
    'Vaadin',
    'VRaptor',
    'Wavemaker',
    'WebObjects',
    'WebWork',
    'ztemplates',
    'AngularJS',
    'Angular',
    'Backbone.js',
    'Ember.js',
    'Express.js',
    'KnockoutJS',
    'Meteor',
    'Node.js',
    'OpenUI5',
    'Polymer',
    'React.js',
    'Redux',
    'Sails.js',
    'Vue.js',
    'Kepler',
    'Lift',
    'Play',
    'Scalatra',
    'Catalyst',
    'Dancer',
    'Mason',
    'Maypole',
    'Mojolicious',
    'Agavi',
    'CakePHP',
    'CodeIgniter',
    'Drupal',
    'Fat-Free',
    'FuelPHP',
    'Gyroscope',
    'Jamroom',
    'Kajona',
    'Kohana',
    'Laravel',
    'Li3 (Lithium)',
    'Nette Framework',
    'Phalcon',
    'Pop PHP',
    'PRADO',
    'Silex',
    'SilverStripe',
    'Smart.Framework',
    'Symfony',
    'TwistPHP',
    'Yii',
    'Zend Framework',
    'Bottle',
    'BlueBream',
    'CherryPy',
    'CubicWeb',
    'Django',
    'Flask',
    'Google App Engine',
    'Grok',
    'Masonite',
    'Nagare',
    'Pyjs',
    'Pylons',
    'Pyramid',
    'TACTIC',
    'Tornado',
    'TurboGears',
    'web2py',
    'Webware',
    'Zope 2',
    'Camping',
    'Merb',
    'Padrino',
    'PureMVC',
    'Ruby on Rails',
    'Sinatra',
    'AIDA/Web',
    'Application Express',
    'Flex',
    'Grails',
    'Morfik',
    'Ocsigen',
    'Opa',
    'OpenACS',
    'Seaside',
    'HTML',
    'CSS',
    'DSSSL',
    'XSL',
    'JSSS',
    'FOSI',
    'Sass',
    'Less',
    'Stylus',
    'SMIL Timesheets',
    'jQuery',
    'GraphQL',
    'Git',
    'npm',
    'Yarn',
    'Docker',
    'Kubernetes'
];
